#!/bin/bash

# What modules, in what order
MODULES="mpd cputemp cpuload ram disksize time date battery "

# Modules that require an active internet connection
ONLINE_MODULES=" localip "

# Delay between showing the status bar
DELAY="0.05"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/custom/"

# Separator between modules
SEPARATOR="  "

# Padding at the end and beggining of the status bar
RIGHT_PADDING=""
LEFT_PADDING=""
